name: Build

on:
  pull_request:
  push:
    branches:
      - "*"

permissions:
  actions: read
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_x86:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - run: "nix flake check --verbose --show-trace"
      - run: "nix build .#god --print-out-paths --verbose --show-trace"
jobs:
  check_arm:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - run: "nix flake check --verbose --show-trace"
      - run: "nix build .#god --print-out-paths --verbose --show-trace"
